import React, {createContext, useContext, useEffect, useMemo, useRef, useState} from 'react';
import {Animated, Dimensions, Easing, KeyboardAvoidingView, PanResponder, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Notifications from 'expo-notifications';
import {StatusBar} from 'expo-status-bar';
import {Video, ResizeMode} from 'expo-av';
import Svg, {Circle, ClipPath, Defs, G, Line, LinearGradient, Rect, Stop, Text as SvgText} from 'react-native-svg';

Notifications.setNotificationHandler({handleNotification: async()=>({shouldShowBanner:true,shouldShowList:true,shouldPlaySound:true,shouldSetBadge:false})});

type Status='pending'|'completed'|'unfinished';
type Workout={id:string;name:string;seconds:number;scheduledAt:string;status:Status;video:string};
type ThemeMode='light'|'dark';
type Profile={name:string;email:string;startHour:number;endHour:number;minMinutes:number;maxMinutes:number;frequency:number;themeMode?:ThemeMode};
const cyan='#2BE7EE', blue='#2786FF', red='#FF665E', yellow='#FFD84D';
type Palette={mode:ThemeMode;bg:string;surface:string;surface2:string;text:string;muted:string;border:string;nav:string;field:string;soft:string;accent:string};
const palettes:Record<ThemeMode,Palette>={
 dark:{mode:'dark',bg:'#041D3D',surface:'#092953',surface2:'#0D3568',text:'#F6FBFF',muted:'#8BA9C5',border:'#174574',nav:'#06244A',field:'#0B315F',soft:'#0A3A67',accent:cyan},
 light:{mode:'light',bg:'#EAF4F8',surface:'#FFFFFF',surface2:'#DCECF4',text:'#08264A',muted:'#638096',border:'#C7DCE7',nav:'#FFFFFF',field:'#F1F8FB',soft:'#D8F1F4',accent:'#007C9C'}
};
const ThemeContext=createContext<Palette>(palettes.dark);
const useStyles=()=>{const theme=useContext(ThemeContext);return useMemo(()=>makeStyles(theme),[theme])};
const exercises=[
  {name:'Bodyweight squats',video:'https://videos.pexels.com/video-files/4761426/4761426-hd_720_1280_25fps.mp4'},
  {name:'Standing knee raises',video:'https://videos.pexels.com/video-files/4753998/4753998-hd_720_1280_25fps.mp4'},
  {name:'Reverse lunges',video:'https://videos.pexels.com/video-files/5319099/5319099-hd_720_1280_25fps.mp4'},
  {name:'Wall push-ups',video:'https://videos.pexels.com/video-files/4754005/4754005-hd_720_1280_25fps.mp4'},
  {name:'Marching in place',video:'https://videos.pexels.com/video-files/4761790/4761790-hd_720_1280_25fps.mp4'}
];
const key='calmmove-v1';
const testKey='calmmove-test-schedule-v12';
const dayKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const niceTime=(iso:string)=>new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const dayLabel=(iso:string)=>{const d=new Date(iso+'T12:00:00'),now=new Date();const diff=Math.abs(+now-+d)/86400000;return diff<7?d.toLocaleDateString([],{weekday:'long'}):d.toLocaleDateString([],{day:'numeric',month:'short',year:'numeric'})};

function FadeIn({children,style}:{children:React.ReactNode;style?:any}){const a=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.timing(a,{toValue:1,duration:420,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start()},[]);return <Animated.View style={[style,{opacity:a,transform:[{translateY:a.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}]}>{children}</Animated.View>}

function planDay(p:Profile,date=new Date()):Workout[]{
  const start=new Date(date);start.setHours(p.startHour,0,0,0);const end=new Date(date);end.setHours(p.endHour,0,0,0);
  const available=Math.floor((+end-+start)/60000);const count=Math.max(1,Math.min(p.frequency,Math.floor(available/20)+1));
  const step=count===1?0:available/(count-1);
  return Array.from({length:count},(_,i)=>{const e=exercises[Math.floor(Math.random()*exercises.length)];const at=new Date(+start+step*i*60000);const seconds=Math.round((p.minMinutes*60+Math.random()*(p.maxMinutes-p.minMinutes)*60)/10)*10;return{id:`${dayKey(date)}-${i}`,name:e.name,seconds,scheduledAt:at.toISOString(),status:'pending',video:e.video};});
}

function testDay(p:Profile,date=new Date()):Workout[]{
 const first=new Date(date);first.setHours(22,0,0,0);const second=new Date(date);second.setHours(23,59,0,0);
 return [
  {id:`${dayKey(date)}-test-2200`,name:'Bodyweight squats',seconds:p.minMinutes*60,scheduledAt:first.toISOString(),status:'pending' as Status,video:exercises[0].video},
  {id:`${dayKey(date)}-test-2359`,name:'Standing knee raises',seconds:p.maxMinutes*60,scheduledAt:second.toISOString(),status:'pending' as Status,video:exercises[1].video}
 ];
}

const Field=({label,value,onChange,keyboard='default'}:{label:string;value:string;onChange:(v:string)=>void;keyboard?:any})=>{const s=useStyles(),theme=useContext(ThemeContext);return <View style={{gap:7}}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard} placeholderTextColor={theme.muted} style={s.input}/></View>};
const Stepper=({label,value,min,max,onChange,suffix=''}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void;suffix?:string})=>{const s=useStyles();return <View style={s.stepRow}><View><Text style={s.label}>{label}</Text><Text style={s.help}>{min}–{max}{suffix}</Text></View><View style={s.stepper}><Pressable style={s.round} onPress={()=>onChange(Math.max(min,value-1))}><Text style={s.roundText}>−</Text></Pressable><Text style={s.stepValue}>{value}{suffix}</Text><Pressable style={s.round} onPress={()=>onChange(Math.min(max,value+1))}><Text style={s.roundText}>+</Text></Pressable></View></View>};

function Setup({onDone}:{onDone:(p:Profile)=>void}){
 const s=useStyles();
 const [name,setName]=useState('');const[email,setEmail]=useState('');const[start,setStart]=useState(8);const[end,setEnd]=useState(16);const[min,setMin]=useState(2);const[max,setMax]=useState(3);const[freq,setFreq]=useState(5);const valid=name.trim()&&/^\S+@\S+\.\S+$/.test(email)&&end>start&&max>=min;
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.setup}><View style={s.logo}><Text style={s.logoText}>CM</Text></View><Text style={s.eyebrow}>WELCOME TO CALMMOVE</Text><Text style={s.title}>Small moves,{"\n"}stronger days.</Text><Text style={s.sub}>Tell us a little about you, then choose when movement reminders fit your day.</Text><View style={s.card}><Field label="Your name" value={name} onChange={setName}/><Field label="Email address" value={email} onChange={setEmail} keyboard="email-address"/></View><Text style={s.section}>Your daily rhythm</Text><View style={s.card}><Stepper label="Start time" value={start} min={0} max={22} onChange={n=>setStart(Math.min(n,end-1))} suffix=":00"/><View style={s.div}/><Stepper label="End time" value={end} min={1} max={23} onChange={n=>setEnd(Math.max(n,start+1))} suffix=":00"/><View style={s.div}/><Stepper label="Minimum workout" value={min} min={1} max={15} onChange={n=>{setMin(n);setMax(Math.max(n,max))}} suffix=" min"/><View style={s.div}/><Stepper label="Maximum workout" value={max} min={1} max={20} onChange={n=>setMax(Math.max(n,min))} suffix=" min"/><View style={s.div}/><Stepper label="Workouts per day" value={freq} min={1} max={100} onChange={setFreq}/><Text style={s.note}>We always leave at least 20 minutes between workouts. If your time window is too short, we’ll schedule the maximum that safely fits.</Text></View><Pressable disabled={!valid} onPress={()=>onDone({name:name.trim(),email:email.trim(),startHour:start,endHour:end,minMinutes:min,maxMinutes:max,frequency:freq,themeMode:'dark'})} style={[s.primary,!valid&&{opacity:.4}]}><Text style={s.primaryText}>Create my plan</Text></Pressable></ScrollView></KeyboardAvoidingView>
}

function Settings({profile,onSave,onLogout}:{profile:Profile;onSave:(p:Profile)=>void;onLogout:()=>void}){
 const s=useStyles();const[name,setName]=useState(profile.name),[email,setEmail]=useState(profile.email),[start,setStart]=useState(profile.startHour),[end,setEnd]=useState(profile.endHour),[min,setMin]=useState(profile.minMinutes),[max,setMax]=useState(profile.maxMinutes),[freq,setFreq]=useState(profile.frequency),[themeMode,setThemeMode]=useState<ThemeMode>(profile.themeMode||'dark');const valid=name.trim()&&/^\S+@\S+\.\S+$/.test(email)&&end>start&&max>=min;
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.settingsPage}><FadeIn style={s.profileHero}><View style={s.profileHeroIcon}><Text style={{fontSize:35}}>🏋️</Text></View><Text style={s.profileName}>{name}</Text><Text style={s.profileEmail}>{email}</Text></FadeIn><FadeIn style={s.card}><Field label="Your name" value={name} onChange={setName}/><Field label="Email address" value={email} onChange={setEmail} keyboard="email-address"/></FadeIn><Text style={s.section}>Appearance</Text><FadeIn style={s.card}><View style={s.themeRow}><View><Text style={s.label}>Colour mode</Text><Text style={s.help}>Choose how CalmMove looks</Text></View><View style={s.themeSwitch}><Pressable onPress={()=>setThemeMode('light')} style={[s.themeOption,themeMode==='light'&&s.themeOptionOn]}><Text style={[s.themeOptionText,themeMode==='light'&&s.themeOptionTextOn]}>☀ Light</Text></Pressable><Pressable onPress={()=>setThemeMode('dark')} style={[s.themeOption,themeMode==='dark'&&s.themeOptionOn]}><Text style={[s.themeOptionText,themeMode==='dark'&&s.themeOptionTextOn]}>● Dark</Text></Pressable></View></View></FadeIn><Text style={s.section}>Workout preferences</Text><FadeIn style={s.card}><Stepper label="Start time" value={start} min={0} max={22} onChange={n=>setStart(Math.min(n,end-1))} suffix=":00"/><View style={s.div}/><Stepper label="End time" value={end} min={1} max={23} onChange={n=>setEnd(Math.max(n,start+1))} suffix=":00"/><View style={s.div}/><Stepper label="Minimum workout" value={min} min={1} max={15} onChange={n=>{setMin(n);setMax(Math.max(n,max))}} suffix=" min"/><View style={s.div}/><Stepper label="Maximum workout" value={max} min={1} max={20} onChange={n=>setMax(Math.max(n,min))} suffix=" min"/><View style={s.div}/><Stepper label="Workouts per day" value={freq} min={1} max={100} onChange={setFreq}/><Text style={s.note}>A new daily plan is created when you save. Workouts remain at least 20 minutes apart.</Text></FadeIn><Pressable disabled={!valid} onPress={()=>onSave({name:name.trim(),email:email.trim(),startHour:start,endHour:end,minMinutes:min,maxMinutes:max,frequency:freq,themeMode})} style={[s.primary,!valid&&{opacity:.4}]}><Text style={s.primaryText}>Save settings</Text></Pressable><Pressable onPress={onLogout} style={s.logout}><Text style={s.logoutText}>Log out</Text></Pressable></ScrollView></KeyboardAvoidingView>
}

function AppHeader({settings,onProfile,onBack}:{settings:boolean;onProfile:()=>void;onBack:()=>void}){const s=useStyles();const float=useRef(new Animated.Value(0)).current;useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(float,{toValue:1,duration:1100,easing:Easing.inOut(Easing.sin),useNativeDriver:true}),Animated.timing(float,{toValue:0,duration:1100,easing:Easing.inOut(Easing.sin),useNativeDriver:true})]));loop.start();return()=>loop.stop()},[]);return <View style={s.appHeader}>{settings?<Pressable onPress={onBack} style={s.backButton}><Text style={s.backText}>‹</Text></Pressable>:<View style={s.brandMark}><Text style={s.brandSpark}>CM</Text></View>}<Text style={s.brandName}>{settings?'PROFILE & SETTINGS':'CALMMOVE'}</Text>{settings?<View style={{width:48}}/>:<Pressable onPress={onProfile} style={s.avatar}><Animated.Text style={[s.avatarEmoji,{transform:[{translateY:float.interpolate({inputRange:[0,1],outputRange:[1,-3]})},{rotate:float.interpolate({inputRange:[0,1],outputRange:['-4deg','4deg']})}]}]}>🏋️</Animated.Text><View style={s.avatarDot}/></Pressable>}</View>}

function NavButton({label,icon,active,onPress}:{label:string;icon:string;active:boolean;onPress:()=>void}){const s=useStyles();const a=useRef(new Animated.Value(active?1:0)).current;useEffect(()=>{Animated.spring(a,{toValue:active?1:0,damping:15,stiffness:160,useNativeDriver:true}).start()},[active]);return <Pressable onPress={onPress} style={s.navItem}><Animated.View style={[s.navBubble,active&&s.navBubbleOn,{transform:[{scale:a.interpolate({inputRange:[0,1],outputRange:[.88,1]})}]}]}><View style={s.navIconWrap}><Text style={[s.navIcon,active&&s.navIconOn]}>{icon}</Text></View></Animated.View><Text style={[s.navText,active&&s.navTextOn]}>{label}</Text></Pressable>}

function Donut({done,total}:{done:number;total:number}){const theme=useContext(ThemeContext);const size=160,r=60,c=2*Math.PI*r,p=total?done/total:0;return <View style={{width:size,height:size,alignItems:'center',justifyContent:'center'}}><Svg width={size} height={size}><G rotation="-90" origin={`${size/2},${size/2}`}><Circle cx={80} cy={80} r={r} stroke={theme.border} strokeWidth={14} fill="none"/><Circle cx={80} cy={80} r={r} stroke={blue} strokeWidth={14} fill="none" strokeLinecap="round" strokeDasharray={`${c*p} ${c}`} /></G><SvgText x={size/2} y={size/2} textAnchor="middle" alignmentBaseline="central" fontSize="27" fontWeight="800" fill={theme.text}>{Math.round(p*100)}%</SvgText></Svg></View>}
function WeekChart({days,onDay}:{days:{key:string;done:number;missed:number;total:number;label:string}[];onDay:(k:string)=>void}){const s=useStyles(),theme=useContext(ThemeContext);const w=Math.min(340,Dimensions.get('window').width-72),h=210,max=Math.max(1,...days.map(d=>d.total)),bw=26,gap=(w-36-bw*7)/6,today=dayKey(new Date());return <View style={s.chartWrap}><Svg width={w} height={h}><Defs><LinearGradient id="blueDepth" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor="#75AEFF"/><Stop offset=".48" stopColor={blue}/><Stop offset="1" stopColor="#1C57C2"/></LinearGradient><LinearGradient id="redDepth" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor="#FF938D"/><Stop offset="1" stopColor="#C9433C"/></LinearGradient>{days.map((d,i)=>{const x=18+i*(bw+gap),height=d.total/max*125;return <ClipPath key={d.key} id={`bar-${i}`}><Rect x={x} y={165-height} width={bw} height={height} rx={8}/></ClipPath>})}</Defs>{[0,.5,1].map((n,i)=><Line key={i} x1="8" x2={w-8} y1={165-n*125} y2={165-n*125} stroke={theme.border}/>) }{days.map((d,i)=>{const x=18+i*(bw+gap),totalHeight=d.total/max*125,doneHeight=d.done/max*125,isToday=d.key===today;return <G key={d.key} onPress={()=>onDay(d.key)}><Rect x={x-8} y={18} width={bw+16} height={180} fill="transparent"/><SvgText x={x+bw/2} y={Math.max(27,157-totalHeight)} textAnchor="middle" fontSize="11" fontWeight="800" fill={theme.text}>{d.total}</SvgText><Rect x={x+4} y={170-totalHeight} width={bw} height={totalHeight} rx={8} fill="#000" opacity={.32}/><G clipPath={`url(#bar-${i})`}><Rect x={x} y={165-totalHeight} width={bw} height={totalHeight} fill="url(#redDepth)"/><Rect x={x} y={165-doneHeight} width={bw} height={doneHeight} fill="url(#blueDepth)"/></G>{d.total>0&&<Line x1={x+4} x2={x+4} y1={169-totalHeight} y2={161} stroke="white" opacity={.34} strokeWidth={2}/>} {isToday&&<Circle cx={x+bw/2} cy={185} r={13} fill={yellow}/>}<SvgText x={x+bw/2} y={189} textAnchor="middle" fontSize="11" fontWeight={isToday?'900':'600'} fill={isToday?'#171916':theme.muted}>{d.label}</SvgText></G>})}</Svg></View>}

function Home({name,all,onHistory}:{name:string;all:Record<string,Workout[]>;onHistory:(k:string)=>void}){const s=useStyles();const today=dayKey(new Date()),tw=all[today]||[],done=tw.filter(x=>x.status==='completed').length;const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const k=dayKey(d),ws=all[k]||[];return{key:k,done:ws.filter(x=>x.status==='completed').length,missed:ws.filter(x=>x.status==='unfinished').length,total:ws.length,label:d.toLocaleDateString([],{weekday:'narrow'})}});return <ScrollView contentContainerStyle={s.page}><FadeIn><Text style={s.hello}>HELLO, {name.toUpperCase()}</Text><Text style={s.title2}>Your movement this week</Text></FadeIn><FadeIn style={s.card}><Text style={s.cardTitle}>Daily workouts</Text><Text style={s.help}>Tap a bar to see that day’s history</Text><WeekChart days={days} onDay={onHistory}/><View style={s.legend}><Text style={{color:blue}}>● Completed</Text><Text style={{color:red}}>● Not completed</Text></View></FadeIn><FadeIn style={[s.card,{alignItems:'center'}]}><Text style={[s.cardTitle,{alignSelf:'flex-start'}]}>Today’s progress</Text><Donut done={done} total={tw.length}/><Text style={s.sub}>{done} of {tw.length} workouts completed</Text></FadeIn></ScrollView>}

function WorkoutCard({w,left,onMark,locked=false,immersive=false}:{w:Workout;left:number;onMark?:(x:Status)=>void;locked?:boolean;immersive?:boolean}){const s=useStyles();const anim=useRef(new Animated.Value(0)).current;useEffect(()=>{anim.setValue(0);Animated.spring(anim,{toValue:1,damping:18,stiffness:95,mass:.8,useNativeDriver:true}).start()},[w.id]);const isReadOnly=locked||w.status!=='pending';return <View style={immersive?s.immersiveCard:undefined}><Text style={s.workoutName}>{w.name}</Text><Text style={s.duration}>{Math.floor(w.seconds/60)} min {w.seconds%60?`${w.seconds%60} sec`:''}</Text><Animated.View style={[s.videoWrap,immersive&&s.videoWrapLarge,{opacity:anim,transform:[{translateX:anim.interpolate({inputRange:[0,1],outputRange:[90,0]})},{scale:anim.interpolate({inputRange:[0,1],outputRange:[.96,1]})}]}]}><Video source={{uri:w.video}} style={s.video} resizeMode={ResizeMode.COVER} shouldPlay isLooping isMuted useNativeControls={false}/><View style={s.videoBadge}><Text style={s.videoBadgeText}>10–20 SEC DEMO</Text></View></Animated.View><Text style={s.left}>{left} workout{left===1?'':'s'} left today</Text>{isReadOnly?<View style={[s.statusPill,w.status==='completed'?s.complete:s.unfinished]}><Text style={s.statusText}>{w.status==='completed'?'✓ Completed':'Not completed'}</Text></View>:<View style={s.actions}><Pressable onPress={()=>onMark?.('completed')} style={[s.action,s.actionComplete]}><Text style={s.actionCompleteText}>✓ Completed</Text></Pressable><Pressable onPress={()=>onMark?.('unfinished')} style={s.action}><Text style={s.actionText}>Not completed</Text></Pressable></View>}{isReadOnly&&<Text style={s.readonly}>{locked?'History is read-only':'Status saved · read-only'}</Text>}</View>}
function Current({workouts,onMark}:{workouts:Workout[];onMark:(id:string,x:Status)=>void}){const s=useStyles();const now=Date.now();const due=workouts.find(x=>x.status==='pending'&&+new Date(x.scheduledAt)<=now);const latest=[...workouts].filter(x=>x.status!=='pending').sort((a,b)=>+new Date(b.scheduledAt)-+new Date(a.scheduledAt))[0];const next=workouts.find(x=>x.status==='pending'&&+new Date(x.scheduledAt)>now);const current=due||latest;if(!current)return <FadeIn style={s.empty}><Text style={{fontSize:40}}>⚡</Text><Text style={s.title2}>Your next movement break</Text><Text style={s.sub}>{next?`Available at ${niceTime(next.scheduledAt)}`:'No workout planned'}</Text></FadeIn>;return <View style={s.workoutPage}><FadeIn style={{alignItems:'center'}}><Text style={s.eyebrow}>{due?'CURRENT WORKOUT':'MOST RECENT WORKOUT'}</Text><Text style={s.when}>{niceTime(current.scheduledAt)}</Text></FadeIn><WorkoutCard w={current} left={workouts.filter(x=>x.status==='pending').length} onMark={x=>onMark(current.id,x)} immersive/>{!due&&next&&<FadeIn style={s.nextNotice}><Text style={s.nextNoticeText}>Next workout available at {niceTime(next.scheduledAt)}</Text></FadeIn>}</View>}
const historyHeight=Math.max(430,Dimensions.get('window').height-305);
function HistorySlide({w,index,total,scrollY}:{w:Workout;index:number;total:number;scrollY:Animated.Value}){const s=useStyles();const range=[(index-1)*historyHeight,index*historyHeight,(index+1)*historyHeight];const scale=scrollY.interpolate({inputRange:range,outputRange:[.965,1,.965],extrapolate:'clamp'});const opacity=scrollY.interpolate({inputRange:range,outputRange:[.58,1,.58],extrapolate:'clamp'});const translateY=scrollY.interpolate({inputRange:range,outputRange:[22,0,-22],extrapolate:'clamp'});return <Animated.View renderToHardwareTextureAndroid style={[s.historySlide,{height:historyHeight,opacity,transform:[{translateY},{scale}]}]}><Text style={s.count}>WORKOUT {index+1} OF {total} · {niceTime(w.scheduledAt)}</Text><WorkoutCard w={w} left={Math.max(0,total-index-1)} locked/><Text style={s.swipeHint}>{index<total-1?'Swipe up for next workout':'End of the day'}</Text></Animated.View>}
function History({all,selected,setSelected}:{all:Record<string,Workout[]>;selected:string;setSelected:(x:string)=>void}){const s=useStyles();const keys=Object.keys(all).sort(),ws=all[selected]||[],scrollY=useRef(new Animated.Value(0)).current;return <View style={s.historyPage}><FadeIn><Text style={s.title2}>Workout history</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.dateRow}>{keys.map(k=><Pressable key={k} onPress={()=>setSelected(k)} style={[s.chip,k===selected&&s.chipOn]}><Text style={[s.chipText,k===selected&&s.chipTextOn]}>{dayLabel(k)}</Text></Pressable>)}</ScrollView><Text style={s.historyDay}>{dayLabel(selected)}</Text></FadeIn>{ws.length?<Animated.FlatList key={selected} data={ws} keyExtractor={w=>w.id} showsVerticalScrollIndicator={false} snapToInterval={historyHeight} snapToAlignment="start" decelerationRate={0.94} disableIntervalMomentum scrollEventThrottle={16} onScroll={Animated.event([{nativeEvent:{contentOffset:{y:scrollY}}}],{useNativeDriver:true})} renderItem={({item,index})=><HistorySlide w={item} index={index} total={ws.length} scrollY={scrollY}/>}/>:<Text style={s.sub}>No workouts for this day.</Text>}</View>}

export default function App(){const[ready,setReady]=useState(false);const[profile,setProfile]=useState<Profile|null>(null);const[all,setAll]=useState<Record<string,Workout[]>>({});const[tab,setTab]=useState<'home'|'workout'|'history'|'settings'>('home');const[returnTab,setReturnTab]=useState<'home'|'workout'|'history'>('home');const[selected,setSelected]=useState(dayKey(new Date()));
 const theme=palettes[profile?.themeMode||'dark'];const s=useMemo(()=>makeStyles(theme),[theme]);
 const swipeX=useRef(new Animated.Value(0)).current;const tabOrder:['home','workout','history']=['home','workout','history'];
 const runSwipe=(direction:-1|1)=>{if(tab==='settings')return;const index=tabOrder.indexOf(tab),next=index+direction;if(next<0||next>=tabOrder.length){Animated.spring(swipeX,{toValue:0,damping:18,stiffness:180,useNativeDriver:true}).start();return}const width=Dimensions.get('window').width;Animated.timing(swipeX,{toValue:direction===1?-width:width,duration:165,easing:Easing.in(Easing.cubic),useNativeDriver:true}).start(()=>{setTab(tabOrder[next]);swipeX.setValue(direction===1?width:-width);Animated.spring(swipeX,{toValue:0,damping:20,stiffness:150,mass:.75,useNativeDriver:true}).start()})};
 const swipeResponder=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>tab!=='settings'&&Math.abs(g.dx)>14&&Math.abs(g.dx)>Math.abs(g.dy)*1.35,onPanResponderMove:(_,g)=>{const index=tab==='settings'?-1:tabOrder.indexOf(tab),atEdge=(index===0&&g.dx>0)||(index===tabOrder.length-1&&g.dx<0);swipeX.setValue(g.dx*(atEdge?.16:.52))},onPanResponderRelease:(_,g)=>{if(Math.abs(g.dx)>68||Math.abs(g.vx)>.5)runSwipe(g.dx<0?1:-1);else Animated.spring(swipeX,{toValue:0,damping:18,stiffness:180,useNativeDriver:true}).start()},onPanResponderTerminate:()=>Animated.spring(swipeX,{toValue:0,damping:18,stiffness:180,useNativeDriver:true}).start()}),[tab]);
 const save=(p:Profile|null,a:Record<string,Workout[]>)=>AsyncStorage.setItem(key,JSON.stringify({profile:p,all:a}));
 const schedule=async(p:Profile,workouts:Workout[])=>{await Notifications.requestPermissionsAsync();if(Platform.OS==='android')await Notifications.setNotificationChannelAsync('workouts',{name:'Workout reminders',importance:Notifications.AndroidImportance.HIGH});for(const w of workouts){const d=new Date(w.scheduledAt);if(+d>Date.now())await Notifications.scheduleNotificationAsync({content:{title:`Time for ${w.name}`,body:`A calm ${Math.ceil(w.seconds/60)}-minute movement break is ready.`,data:{workoutId:w.id}},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:d,channelId:'workouts'}})}};
 useEffect(()=>{(async()=>{const raw=await AsyncStorage.getItem(key);if(raw){const d=JSON.parse(raw),stored=d.profile as Profile,p=stored?{...stored,themeMode:stored.themeMode||'dark' as ThemeMode}:stored;let a=d.all||{};if(p&&!await AsyncStorage.getItem(testKey)){const tests=testDay(p),today=dayKey(new Date());a={...a,[today]:tests};await Notifications.cancelAllScheduledNotificationsAsync();await schedule(p,tests);await AsyncStorage.setItem(testKey,'added');await save(p,a)}setProfile(p);setAll(a)}setReady(true)})()},[]);
 const finishSetup=async(p:Profile)=>{const today=dayKey(new Date()),planned=testDay(p),demoDays:Record<string,Workout[]>={};for(let i=1;i<=6;i++){const d=new Date();d.setDate(d.getDate()-i);demoDays[dayKey(d)]=planDay(p,d).map((w,j)=>({...w,status:(j+i)%3?'completed':'unfinished'}))}const a={...demoDays,[today]:planned};setProfile(p);setAll(a);await save(p,a);await AsyncStorage.setItem(testKey,'added');await Notifications.cancelAllScheduledNotificationsAsync();await schedule(p,planned)};
 useEffect(()=>{if(!profile)return;const k=dayKey(new Date());if(!all[k]){const ws=planDay(profile),a={...all,[k]:ws};setAll(a);save(profile,a);schedule(profile,ws)}},[profile]);
 const mark=(id:string,status:Status)=>{const k=dayKey(new Date()),a={...all,[k]:(all[k]||[]).map(w=>w.id===id?{...w,status}:w)};setAll(a);save(profile,a)};
 const openSettings=()=>{if(tab!=='settings')setReturnTab(tab);setTab('settings')};
 const updateSettings=async(p:Profile)=>{const today=dayKey(new Date()),tests=testDay(p),a={...all,[today]:tests};setProfile(p);setAll(a);await save(p,a);await Notifications.cancelAllScheduledNotificationsAsync();await schedule(p,tests);setTab('home')};
 const logout=async()=>{await Notifications.cancelAllScheduledNotificationsAsync();await AsyncStorage.multiRemove([key,testKey]);setProfile(null);setAll({});setTab('home')};
 if(!ready)return null;if(!profile)return <ThemeContext.Provider value={theme}><SafeAreaView style={s.safe}><StatusBar style="light"/><Setup onDone={finishSetup}/></SafeAreaView></ThemeContext.Provider>;
 const goHistory=(k:string)=>{setSelected(k);setTab('history')};return <ThemeContext.Provider value={theme}><SafeAreaView style={s.safe}><StatusBar style={theme.mode==='dark'?'light':'dark'}/><AppHeader settings={tab==='settings'} onProfile={openSettings} onBack={()=>setTab(returnTab)}/><Animated.View {...(tab==='settings'?{}:swipeResponder.panHandlers)} style={{flex:1,transform:[{translateX:swipeX}],opacity:swipeX.interpolate({inputRange:[-Dimensions.get('window').width,0,Dimensions.get('window').width],outputRange:[.72,1,.72],extrapolate:'clamp'})}}>{tab==='home'?<Home name={profile.name} all={all} onHistory={goHistory}/>:tab==='workout'?<Current workouts={all[dayKey(new Date())]||[]} onMark={mark}/>:tab==='history'?<History all={all} selected={selected} setSelected={setSelected}/>:<Settings profile={profile} onSave={updateSettings} onLogout={logout}/>}</Animated.View>{tab!=='settings'&&<View style={s.nav}><NavButton label="Home" icon="⌂" active={tab==='home'} onPress={()=>setTab('home')}/><NavButton label="Workout" icon="▶" active={tab==='workout'} onPress={()=>setTab('workout')}/><NavButton label="History" icon="↻" active={tab==='history'} onPress={()=>setTab('history')}/></View>}</SafeAreaView></ThemeContext.Provider>}

const makeStyles=(t:Palette)=>StyleSheet.create({
 safe:{flex:1,backgroundColor:t.bg},setup:{padding:24,paddingBottom:50,gap:18},settingsPage:{padding:20,paddingBottom:45,gap:17},page:{padding:20,paddingTop:8,paddingBottom:40,gap:18},
 appHeader:{height:64,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:t.bg},brandMark:{width:48,height:48,borderRadius:15,backgroundColor:t.accent,alignItems:'center',justifyContent:'center'},brandSpark:{fontSize:15,fontWeight:'900',color:t.mode==='dark'?'#041D3D':'#FFF',letterSpacing:-1},brandName:{fontSize:16,fontWeight:'900',color:t.text,letterSpacing:1.2},avatar:{width:48,height:48,borderRadius:24,backgroundColor:t.surface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:t.border,shadowColor:'#000',shadowOpacity:.3,shadowRadius:8,elevation:5},avatarEmoji:{fontSize:25},avatarDot:{position:'absolute',right:1,bottom:2,width:11,height:11,borderRadius:6,backgroundColor:t.accent,borderWidth:2,borderColor:t.surface},backButton:{width:48,height:48,borderRadius:24,backgroundColor:t.surface,alignItems:'center',justifyContent:'center'},backText:{fontSize:36,lineHeight:38,color:t.text},
 profileHero:{alignItems:'center',paddingVertical:12},profileHeroIcon:{width:84,height:84,borderRadius:42,backgroundColor:t.accent,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:t.surface,shadowColor:'#000',shadowOpacity:.35,shadowRadius:14,elevation:7},profileName:{fontSize:24,fontWeight:'900',color:t.text,marginTop:10},profileEmail:{fontSize:13,color:t.muted,marginTop:3},
 logo:{width:58,height:58,borderRadius:18,backgroundColor:t.accent,alignItems:'center',justifyContent:'center',marginTop:18},logoText:{fontSize:19,fontWeight:'900',color:t.mode==='dark'?'#041D3D':'#FFF',letterSpacing:-1},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.6,color:t.accent},title:{fontSize:38,lineHeight:43,fontWeight:'900',color:t.text,letterSpacing:-1.3},title2:{fontSize:28,fontWeight:'900',color:t.text,letterSpacing:-.8},hello:{marginTop:8,color:t.accent,fontSize:11,letterSpacing:1.3,fontWeight:'900'},sub:{fontSize:15,lineHeight:22,color:t.muted},section:{fontSize:18,fontWeight:'900',color:t.text,marginTop:6},
 card:{backgroundColor:t.surface,padding:18,borderRadius:18,gap:15,borderWidth:1,borderColor:t.border,shadowColor:'#001124',shadowOpacity:t.mode==='dark'?.52:.13,shadowOffset:{width:0,height:9},shadowRadius:18,elevation:7},chartWrap:{width:'100%',alignSelf:'center',alignItems:'center',justifyContent:'center',overflow:'visible'},label:{fontSize:13,fontWeight:'800',color:t.text},help:{fontSize:12,color:t.muted,marginTop:3},input:{borderWidth:1,borderColor:t.border,borderRadius:12,padding:14,fontSize:16,color:t.text,backgroundColor:t.field},stepRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},stepper:{flexDirection:'row',alignItems:'center',gap:12},round:{width:36,height:36,borderRadius:18,backgroundColor:t.surface2,alignItems:'center',justifyContent:'center'},roundText:{fontSize:22,color:t.accent,fontWeight:'800'},stepValue:{fontWeight:'900',color:t.text,minWidth:62,textAlign:'center'},div:{height:1,backgroundColor:t.border},note:{fontSize:12,lineHeight:18,color:t.muted,backgroundColor:t.soft,padding:12,borderRadius:12},primary:{backgroundColor:t.accent,padding:17,borderRadius:7,alignItems:'center'},primaryText:{color:t.mode==='dark'?'#041D3D':'#FFF',fontSize:16,fontWeight:'900'},logout:{borderWidth:1,borderColor:red,padding:16,borderRadius:12,alignItems:'center',backgroundColor:t.surface},logoutText:{color:red,fontSize:15,fontWeight:'900'},cardTitle:{fontSize:17,fontWeight:'900',color:t.text},legend:{flexDirection:'row',gap:18,justifyContent:'center'},
 themeRow:{gap:14},themeSwitch:{flexDirection:'row',padding:4,borderRadius:14,backgroundColor:t.field,gap:4},themeOption:{flex:1,paddingVertical:11,borderRadius:10,alignItems:'center'},themeOptionOn:{backgroundColor:t.accent},themeOptionText:{color:t.muted,fontWeight:'800'},themeOptionTextOn:{color:t.mode==='dark'?'#041D3D':'#FFF'},
 workoutPage:{flex:1,paddingHorizontal:12,paddingTop:6,paddingBottom:8,alignItems:'center'},immersiveCard:{width:'100%',alignItems:'center',flex:1},workoutName:{fontSize:30,fontWeight:'900',color:t.text,textAlign:'center',marginTop:7},duration:{color:t.accent,fontSize:17,fontWeight:'800',textAlign:'center',marginTop:3,marginBottom:10},when:{fontSize:14,color:t.muted,marginTop:5},videoWrap:{height:340,width:Dimensions.get('window').width-44,borderRadius:22,overflow:'hidden',backgroundColor:t.surface2,borderWidth:1,borderColor:t.border,shadowColor:'#001124',shadowOpacity:.55,shadowRadius:14,elevation:8},videoWrapLarge:{height:Math.min(430,Dimensions.get('window').height*.46),width:Dimensions.get('window').width-24,borderRadius:24},video:{width:'100%',height:'100%'},videoBadge:{position:'absolute',top:14,right:14,backgroundColor:'rgba(3,24,51,.86)',paddingVertical:7,paddingHorizontal:10,borderRadius:7},videoBadgeText:{color:cyan,fontSize:10,fontWeight:'900',letterSpacing:.4},left:{textAlign:'center',marginVertical:11,color:t.muted,fontWeight:'800'},actions:{flexDirection:'row',gap:10,width:'100%'},action:{flex:1,borderWidth:1,borderColor:t.border,borderRadius:10,paddingVertical:15,alignItems:'center',backgroundColor:t.surface},actionComplete:{backgroundColor:blue,borderColor:blue},actionText:{color:t.text,fontWeight:'900'},actionCompleteText:{color:'#FFF',fontWeight:'900'},complete:{backgroundColor:blue,borderColor:blue},unfinished:{backgroundColor:red,borderColor:red},statusPill:{width:'100%',borderRadius:10,paddingVertical:15,alignItems:'center'},statusText:{color:'#FFF',fontWeight:'900'},readonly:{textAlign:'center',marginTop:7,color:t.muted,fontSize:12},nextNotice:{backgroundColor:t.soft,paddingVertical:9,paddingHorizontal:18,borderRadius:12,marginTop:4},nextNoticeText:{color:t.accent,fontWeight:'900',fontSize:12},empty:{flex:1,alignItems:'center',justifyContent:'center',gap:12},
 chip:{paddingVertical:9,paddingHorizontal:13,borderRadius:18,backgroundColor:t.surface,borderWidth:1,borderColor:t.border},chipOn:{backgroundColor:t.accent,borderColor:t.accent},chipText:{color:t.text,fontWeight:'800'},chipTextOn:{color:t.mode==='dark'?'#041D3D':'#FFF'},historyPage:{flex:1,paddingTop:5},dateRow:{gap:8,paddingHorizontal:18,paddingVertical:9},historyDay:{fontSize:17,fontWeight:'900',color:t.text,paddingHorizontal:18,paddingBottom:4},historySlide:{width:Dimensions.get('window').width,paddingHorizontal:12,paddingTop:3,paddingBottom:6,alignItems:'center',justifyContent:'center'},count:{fontSize:11,fontWeight:'900',color:t.accent,letterSpacing:1,margin:4},swipeHint:{fontSize:11,color:t.muted,marginTop:5},
 nav:{height:82,flexDirection:'row',backgroundColor:t.nav,borderTopWidth:1,borderTopColor:t.border,paddingHorizontal:18,shadowColor:'#001124',shadowOpacity:.5,shadowRadius:14,elevation:12},navItem:{flex:1,alignItems:'center',justifyContent:'center',gap:2},navBubble:{width:46,height:46,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:'transparent'},navBubbleOn:{backgroundColor:t.accent,shadowColor:t.accent,shadowOpacity:.38,shadowRadius:10,elevation:7},navIconWrap:{width:26,height:26,alignItems:'center',justifyContent:'center'},navIcon:{width:26,height:26,lineHeight:26,textAlign:'center',textAlignVertical:'center',includeFontPadding:false,fontSize:21,color:t.muted},navIconOn:{color:t.mode==='dark'?'#041D3D':'#FFF'},navText:{fontSize:10,color:t.muted,fontWeight:'700'},navTextOn:{color:t.accent,fontWeight:'900'}
});
